[project]
name = "vizer"
version = "0.1.0"
description = "Data Visualization Application"
requires-python = ">=3.7"
dependencies = [
    "trame<3",
    "sympy>=1.11",
    "quantiphy==2.19",
]

[project.optional-dependencies]
dev = [
    "pytest"
]
